const fs = require("fs-extra");
const path = require("node:path");
const chalk = require("chalk");

/**
 * BMSC Module Installer
 * Installs the BMad Strategy Consulting module for German SME AI strategy consulting
 *
 * @param {Object} options - Installation options
 * @param {string} options.projectRoot - The root directory of the target project
 * @param {Object} options.config - Module configuration from install-config.yaml
 * @param {Array<string>} options.installedIDEs - Array of IDE codes that were installed
 * @param {Object} options.logger - Logger instance for output
 * @returns {Promise<boolean>} - Success status
 */
async function install(options) {
  const { projectRoot, config, installedIDEs, logger } = options;

  try {
    logger.log(chalk.blue("🎯 Installing BMSC Module..."));

    // Create output directory if configured
    if (config["output_folder"]) {
      // Strip {project-root}/ prefix if present
      const outputConfig = config["output_folder"].replace("{project-root}/", "");
      const outputPath = path.join(projectRoot, outputConfig);
      if (!(await fs.pathExists(outputPath))) {
        logger.log(chalk.yellow(`Creating BMSC output directory: ${outputConfig}`));
        await fs.ensureDir(outputPath);

        // Create a README in the output directory
        const readmePath = path.join(outputPath, "README.md");
        const readmeContent = `# BMSC Strategic Roadmaps

This directory contains strategic AI roadmap documents generated by the BMSC (BMad Strategy Consulting) module.

## Document Types

- **STRATEGIC_ROADMAP-*.md** - Comprehensive strategic blueprints for AI implementations
- **ROI_CALCULATION-*.md** - Detailed Activity-Based Costing analyses

## Confidentiality

All documents in this directory are **VERTRAULICH (Confidential)** and contain:

- Financial projections and ROI calculations
- GDPR risk assessments
- Technical architecture recommendations
- Implementation roadmaps

**Do NOT commit these files to public repositories.**

## Generated By

BMAD Strategy Consulting Module (BMSC)
"Ordnung muss sein" - With mathematical rigor, not AI hype.
`;

        await fs.writeFile(readmePath, readmeContent, "utf8");
        logger.log(chalk.green("✓ Created output directory with README"));

        // Create .gitignore to prevent accidental commits
        const gitignorePath = path.join(outputPath, ".gitignore");
        const gitignoreContent = `# BMSC Generated Files - Confidential
*.md
!README.md

# Exclude all strategic documents by default
STRATEGIC_ROADMAP-*.md
ROI_CALCULATION-*.md
`;
        await fs.writeFile(gitignorePath, gitignoreContent, "utf8");
        logger.log(chalk.green("✓ Created .gitignore for confidential documents"));
      }
    }

    // Validate tools directory exists
    const modulePath = path.join(projectRoot, config["bmad_folder"] || ".bmad", "bmsc");
    const toolsPath = path.join(modulePath, "tools");

    if (await fs.pathExists(toolsPath)) {
      logger.log(chalk.green("✓ BMSC financial tools and report generator available"));
    } else {
      logger.log(chalk.yellow("⚠️  BMSC tools directory not found - may need manual verification"));
    }

    // Handle IDE-specific configurations if needed
    if (installedIDEs && installedIDEs.length > 0) {
      logger.log(chalk.cyan(`Configuring BMSC for IDEs: ${installedIDEs.join(", ")}`));

      for (const ide of installedIDEs) {
        await configureForIDE(ide, projectRoot, config, logger);
      }
    }

    // Display installation summary
    logger.log(chalk.green("\n✓ BMSC Module installation complete\n"));
    logger.log(chalk.cyan("📋 Quick Start:"));
    logger.log(chalk.white("  1. Load the Strategy Coach agent:"));
    logger.log(chalk.gray("     agent bmsc/strategy-coach"));
    logger.log(chalk.white("  2. Start consulting session:"));
    logger.log(chalk.gray("     *consult-sme"));
    logger.log(chalk.white("  3. Or run workflow directly:"));
    logger.log(chalk.gray("     workflow german-sme-consult\n"));

    logger.log(chalk.yellow("⚠️  Important Notes:"));
    logger.log(
      chalk.white("  • This module uses German business terminology (DSGVO, Betriebsrat, etc.)"),
    );
    logger.log(chalk.white("  • ROI calculations use Activity-Based Costing methodology"));
    logger.log(chalk.white("  • Generated documents are marked CONFIDENTIAL - do not share publicly"));
    logger.log(chalk.white("  • This provides strategic consulting, NOT legal advice\n"));

    return true;
  } catch (error) {
    logger.error(chalk.red(`Error installing BMSC module: ${error.message}`));
    return false;
  }
}

/**
 * Configure BMSC module for specific IDE
 * @private
 */
async function configureForIDE(ide, projectRoot, config, logger) {
  switch (ide) {
    case "claude-code": {
      // Claude Code specific BMSC configurations
      logger.log(chalk.gray("  • Configured BMSC for Claude Code"));
      break;
    }
    case "cursor": {
      // Cursor specific BMSC configurations
      logger.log(chalk.gray("  • Configured BMSC for Cursor"));
      break;
    }
    case "windsurf": {
      // Windsurf specific BMSC configurations
      logger.log(chalk.gray("  • Configured BMSC for Windsurf"));
      break;
    }
    default: {
      // No specific configuration needed
      logger.log(chalk.gray(`  • BMSC compatible with ${ide}`));
      break;
    }
  }
}

module.exports = { install };
